input ProductInput {
  id: String!
}

type SubProduct {
  id: String!
  name: String!
}

type Product {
  id: String!
  name: String!
  subProducts: [SubProduct!]!
}

extend type Query {
  product(input: ProductInput!): Product
}