version: '3.7'

services:

  app:
    command: npm run start:dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgresql://root:password@db:5432/marsbased-test
      NODE_ENV: 'dev'
    build:
      context: .
      args:
        port: 3000
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marsbased-test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - dbvolume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dbvolume:
  node_modules: